spring:
  application:
    name: chatbot
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: suno
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
